[package]
name = "dodge_the_creeps"
version = "0.1.0"
authors = ["The godot-rust developers"]
publish = false
edition = "2018"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = { path = "../../gdnative" }
rand = "0.8"
