[package]
name = "signals"
version = "0.1.0"
authors = ["The godot-rust developers"]
edition = "2018"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = { path = "../../gdnative" }
