
name: rust
description: "Install Rust toolchain, with caching"

inputs:
  rust:
    required: false
    description: "Rust toolchain, e.g. 'stable' or 'nightly'"
    default: stable
  components:
    required: false
    description: "Components array"
    default: ''
  cache-key:
    required: false
    description: "Extra key to resolve cache"
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ inputs.rust }}
        override: true # use selected toolchain for remainder of this step
        components: ${{ inputs.components }}

    # For notes about the cache, see 'Full CI' workflow
    - uses: Swatinem/rust-cache@v1
      with:
        sharedKey: ${{ inputs.cache-key }}
